### ISSUE TITLE
Call for Maintainers?

### ISSUE THREAD

**Issue by yorammi** [jenkinsci/tikal-multijob-plugin#217]
Does anyone want to become a maintainer of this plugin???
This plugin was very popular for many years, but since most of Jenkins usage now is based on Jenkins Pipeline, and the 'parallel' step along with 'BlueOcean' can basically do whatever this plugin does, it is no longer in [Tikal's radar](https://fullstackradar.tikalk.com/tikal/radar/index.html).
Also, we published the [parallelPhase library class](https://github.com/TikalCI/tci-library/blob/master/src/tci/pipeline/parallelPhase.groovy) that can do in pipelines what the plugin does.
Still, there are many users of the plugin that asked for fixes and new features, so we'll appreciate anyone willing to become a maintainer of the plugin.

**Comment by oshmyrko** [comment]
It's a pity that this plugin has been deprecated, since it is still widely used, and Jenkins Pipeline cannot cover all the features and needs that this plugin does.

I'm using it on my projects and here is an example of public usage by Elastic:
* https://devops-ci.elastic.co/view/Helm%20Charts/job/elastic+helm-charts+7.17/

It allows to connect different Jenkins jobs into single pipeline, and does not require to make changes in case you rename any job from this pipeline, etc. Jenkins Pipelines have a lot of unresolved issues (e.g. parameters are updated only after the pipeline was run, etc).

**Comment by cloph** [comment]
indeed it is unfortunate that it is deprecated while pipeline is not really a drop-in replacement. Besides the lack of proper visualization in pipeline, especially with parallel jobs (that problem is solved to some degree by blueocean), pipeline jobs don't offer a replacement for 
 * resume build (only rebuilding failed jobs)
 * rule-based auto-retry
 * passing job parameters to other builds  (awkward/need to set each individually in pipeline)

**Comment by anic** [comment]
it's so sad to know multi-job plugin to become deprecated, and hope it to be maintained continuously. 

I think pipeline cannot take place of multi-job plugin for
- base on web-ui
- friendly to beginner
- easily to configure

**Comment by balakine** [comment]
The plugin is still deprecated, but it's maintained.
